// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email.proto

package email

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddEmailResponse_Status int32

const (
	AddEmailResponse_FAILURE         AddEmailResponse_Status = 0
	AddEmailResponse_SUCCESS         AddEmailResponse_Status = 1
	AddEmailResponse_DUPLICATE_EMAIL AddEmailResponse_Status = 2
)

var AddEmailResponse_Status_name = map[int32]string{
	0: "FAILURE",
	1: "SUCCESS",
	2: "DUPLICATE_EMAIL",
}

var AddEmailResponse_Status_value = map[string]int32{
	"FAILURE":         0,
	"SUCCESS":         1,
	"DUPLICATE_EMAIL": 2,
}

func (x AddEmailResponse_Status) String() string {
	return proto.EnumName(AddEmailResponse_Status_name, int32(x))
}

func (AddEmailResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{2, 0}
}

type GetEmailsResponse_Status int32

const (
	GetEmailsResponse_FAILURE   GetEmailsResponse_Status = 0
	GetEmailsResponse_SUCCESS   GetEmailsResponse_Status = 1
	GetEmailsResponse_NOT_FOUND GetEmailsResponse_Status = 2
)

var GetEmailsResponse_Status_name = map[int32]string{
	0: "FAILURE",
	1: "SUCCESS",
	2: "NOT_FOUND",
}

var GetEmailsResponse_Status_value = map[string]int32{
	"FAILURE":   0,
	"SUCCESS":   1,
	"NOT_FOUND": 2,
}

func (x GetEmailsResponse_Status) String() string {
	return proto.EnumName(GetEmailsResponse_Status_name, int32(x))
}

func (GetEmailsResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{6, 0}
}

type ValidateEmailResponse_Status int32

const (
	ValidateEmailResponse_FAILURE   ValidateEmailResponse_Status = 0
	ValidateEmailResponse_SUCCESS   ValidateEmailResponse_Status = 1
	ValidateEmailResponse_NOT_FOUND ValidateEmailResponse_Status = 2
)

var ValidateEmailResponse_Status_name = map[int32]string{
	0: "FAILURE",
	1: "SUCCESS",
	2: "NOT_FOUND",
}

var ValidateEmailResponse_Status_value = map[string]int32{
	"FAILURE":   0,
	"SUCCESS":   1,
	"NOT_FOUND": 2,
}

func (x ValidateEmailResponse_Status) String() string {
	return proto.EnumName(ValidateEmailResponse_Status_name, int32(x))
}

func (ValidateEmailResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{8, 0}
}

type SetPrimaryEmailResponse_Status int32

const (
	SetPrimaryEmailResponse_FAILURE   SetPrimaryEmailResponse_Status = 0
	SetPrimaryEmailResponse_SUCCESS   SetPrimaryEmailResponse_Status = 1
	SetPrimaryEmailResponse_NOT_FOUND SetPrimaryEmailResponse_Status = 2
)

var SetPrimaryEmailResponse_Status_name = map[int32]string{
	0: "FAILURE",
	1: "SUCCESS",
	2: "NOT_FOUND",
}

var SetPrimaryEmailResponse_Status_value = map[string]int32{
	"FAILURE":   0,
	"SUCCESS":   1,
	"NOT_FOUND": 2,
}

func (x SetPrimaryEmailResponse_Status) String() string {
	return proto.EnumName(SetPrimaryEmailResponse_Status_name, int32(x))
}

func (SetPrimaryEmailResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{10, 0}
}

type GetUserResponse_Status int32

const (
	GetUserResponse_FAILURE   GetUserResponse_Status = 0
	GetUserResponse_SUCCESS   GetUserResponse_Status = 1
	GetUserResponse_NOT_FOUND GetUserResponse_Status = 2
)

var GetUserResponse_Status_name = map[int32]string{
	0: "FAILURE",
	1: "SUCCESS",
	2: "NOT_FOUND",
}

var GetUserResponse_Status_value = map[string]int32{
	"FAILURE":   0,
	"SUCCESS":   1,
	"NOT_FOUND": 2,
}

func (x GetUserResponse_Status) String() string {
	return proto.EnumName(GetUserResponse_Status_name, int32(x))
}

func (GetUserResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{12, 0}
}

// EmailInfo provides the most important information about an email address.
type EmailInfo struct {
	// EmailId is the internal ID of the email address.
	EmailId uint64 `protobuf:"varint,1,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	// Email is the full email address.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// IsValidated is true if ValidateEmail was called for this email address.
	IsValidated bool `protobuf:"varint,3,opt,name=is_validated,json=isValidated,proto3" json:"is_validated,omitempty"`
	// IsPrimary is true if SetPrimaryEmail was called for this address.
	IsPrimary            bool     `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailInfo) Reset()         { *m = EmailInfo{} }
func (m *EmailInfo) String() string { return proto.CompactTextString(m) }
func (*EmailInfo) ProtoMessage()    {}
func (*EmailInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{0}
}

func (m *EmailInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailInfo.Unmarshal(m, b)
}
func (m *EmailInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailInfo.Marshal(b, m, deterministic)
}
func (m *EmailInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailInfo.Merge(m, src)
}
func (m *EmailInfo) XXX_Size() int {
	return xxx_messageInfo_EmailInfo.Size(m)
}
func (m *EmailInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EmailInfo proto.InternalMessageInfo

func (m *EmailInfo) GetEmailId() uint64 {
	if m != nil {
		return m.EmailId
	}
	return 0
}

func (m *EmailInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EmailInfo) GetIsValidated() bool {
	if m != nil {
		return m.IsValidated
	}
	return false
}

func (m *EmailInfo) GetIsPrimary() bool {
	if m != nil {
		return m.IsPrimary
	}
	return false
}

type AddEmailRequest struct {
	// User that owns the email address.
	User uint64 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	// Email is the complete email address that will be added to the user.
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEmailRequest) Reset()         { *m = AddEmailRequest{} }
func (m *AddEmailRequest) String() string { return proto.CompactTextString(m) }
func (*AddEmailRequest) ProtoMessage()    {}
func (*AddEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{1}
}

func (m *AddEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEmailRequest.Unmarshal(m, b)
}
func (m *AddEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEmailRequest.Marshal(b, m, deterministic)
}
func (m *AddEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEmailRequest.Merge(m, src)
}
func (m *AddEmailRequest) XXX_Size() int {
	return xxx_messageInfo_AddEmailRequest.Size(m)
}
func (m *AddEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddEmailRequest proto.InternalMessageInfo

func (m *AddEmailRequest) GetUser() uint64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *AddEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AddEmailResponse struct {
	// Status of the request.
	Status AddEmailResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=email.AddEmailResponse_Status" json:"status,omitempty"`
	// EmailId of the newly added email address.
	EmailId              uint64   `protobuf:"varint,2,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEmailResponse) Reset()         { *m = AddEmailResponse{} }
func (m *AddEmailResponse) String() string { return proto.CompactTextString(m) }
func (*AddEmailResponse) ProtoMessage()    {}
func (*AddEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{2}
}

func (m *AddEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEmailResponse.Unmarshal(m, b)
}
func (m *AddEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEmailResponse.Marshal(b, m, deterministic)
}
func (m *AddEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEmailResponse.Merge(m, src)
}
func (m *AddEmailResponse) XXX_Size() int {
	return xxx_messageInfo_AddEmailResponse.Size(m)
}
func (m *AddEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddEmailResponse proto.InternalMessageInfo

func (m *AddEmailResponse) GetStatus() AddEmailResponse_Status {
	if m != nil {
		return m.Status
	}
	return AddEmailResponse_FAILURE
}

func (m *AddEmailResponse) GetEmailId() uint64 {
	if m != nil {
		return m.EmailId
	}
	return 0
}

type RemoveEmailRequest struct {
	// User that owns the email address.
	User uint64 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	// EmailId of the email address.
	EmailId              uint64   `protobuf:"varint,2,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveEmailRequest) Reset()         { *m = RemoveEmailRequest{} }
func (m *RemoveEmailRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveEmailRequest) ProtoMessage()    {}
func (*RemoveEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{3}
}

func (m *RemoveEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveEmailRequest.Unmarshal(m, b)
}
func (m *RemoveEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveEmailRequest.Marshal(b, m, deterministic)
}
func (m *RemoveEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveEmailRequest.Merge(m, src)
}
func (m *RemoveEmailRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveEmailRequest.Size(m)
}
func (m *RemoveEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveEmailRequest proto.InternalMessageInfo

func (m *RemoveEmailRequest) GetUser() uint64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *RemoveEmailRequest) GetEmailId() uint64 {
	if m != nil {
		return m.EmailId
	}
	return 0
}

type RemoveEmailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveEmailResponse) Reset()         { *m = RemoveEmailResponse{} }
func (m *RemoveEmailResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveEmailResponse) ProtoMessage()    {}
func (*RemoveEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{4}
}

func (m *RemoveEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveEmailResponse.Unmarshal(m, b)
}
func (m *RemoveEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveEmailResponse.Marshal(b, m, deterministic)
}
func (m *RemoveEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveEmailResponse.Merge(m, src)
}
func (m *RemoveEmailResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveEmailResponse.Size(m)
}
func (m *RemoveEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveEmailResponse proto.InternalMessageInfo

type GetEmailsRequest struct {
	// User that requests his emails.
	User                 uint64   `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEmailsRequest) Reset()         { *m = GetEmailsRequest{} }
func (m *GetEmailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailsRequest) ProtoMessage()    {}
func (*GetEmailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{5}
}

func (m *GetEmailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailsRequest.Unmarshal(m, b)
}
func (m *GetEmailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailsRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailsRequest.Merge(m, src)
}
func (m *GetEmailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailsRequest.Size(m)
}
func (m *GetEmailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailsRequest proto.InternalMessageInfo

func (m *GetEmailsRequest) GetUser() uint64 {
	if m != nil {
		return m.User
	}
	return 0
}

type GetEmailsResponse struct {
	// Status of the request.
	Status GetEmailsResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=email.GetEmailsResponse_Status" json:"status,omitempty"`
	// Emails of the user.
	Emails               []*EmailInfo `protobuf:"bytes,2,rep,name=emails,proto3" json:"emails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetEmailsResponse) Reset()         { *m = GetEmailsResponse{} }
func (m *GetEmailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailsResponse) ProtoMessage()    {}
func (*GetEmailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{6}
}

func (m *GetEmailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailsResponse.Unmarshal(m, b)
}
func (m *GetEmailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailsResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailsResponse.Merge(m, src)
}
func (m *GetEmailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailsResponse.Size(m)
}
func (m *GetEmailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailsResponse proto.InternalMessageInfo

func (m *GetEmailsResponse) GetStatus() GetEmailsResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetEmailsResponse_FAILURE
}

func (m *GetEmailsResponse) GetEmails() []*EmailInfo {
	if m != nil {
		return m.Emails
	}
	return nil
}

type ValidateEmailRequest struct {
	// User that wants to validate his email address.
	User uint64 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	// EmailId of the email address that should be validated.
	// The VALIDATED tag will be attached to this email address.
	EmailId              uint64   `protobuf:"varint,2,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateEmailRequest) Reset()         { *m = ValidateEmailRequest{} }
func (m *ValidateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateEmailRequest) ProtoMessage()    {}
func (*ValidateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{7}
}

func (m *ValidateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateEmailRequest.Unmarshal(m, b)
}
func (m *ValidateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateEmailRequest.Marshal(b, m, deterministic)
}
func (m *ValidateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateEmailRequest.Merge(m, src)
}
func (m *ValidateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateEmailRequest.Size(m)
}
func (m *ValidateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateEmailRequest proto.InternalMessageInfo

func (m *ValidateEmailRequest) GetUser() uint64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *ValidateEmailRequest) GetEmailId() uint64 {
	if m != nil {
		return m.EmailId
	}
	return 0
}

type ValidateEmailResponse struct {
	// Status of the request.
	Status               ValidateEmailResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=email.ValidateEmailResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ValidateEmailResponse) Reset()         { *m = ValidateEmailResponse{} }
func (m *ValidateEmailResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateEmailResponse) ProtoMessage()    {}
func (*ValidateEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{8}
}

func (m *ValidateEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateEmailResponse.Unmarshal(m, b)
}
func (m *ValidateEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateEmailResponse.Marshal(b, m, deterministic)
}
func (m *ValidateEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateEmailResponse.Merge(m, src)
}
func (m *ValidateEmailResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateEmailResponse.Size(m)
}
func (m *ValidateEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateEmailResponse proto.InternalMessageInfo

func (m *ValidateEmailResponse) GetStatus() ValidateEmailResponse_Status {
	if m != nil {
		return m.Status
	}
	return ValidateEmailResponse_FAILURE
}

type SetPrimaryEmailRequest struct {
	// User that sent the request.
	User uint64 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	// EmailId of the email address to set as primary email.
	// Attaches the PRIMARY tag to the email and removes it from the old primary email.
	EmailId              uint64   `protobuf:"varint,2,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPrimaryEmailRequest) Reset()         { *m = SetPrimaryEmailRequest{} }
func (m *SetPrimaryEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SetPrimaryEmailRequest) ProtoMessage()    {}
func (*SetPrimaryEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{9}
}

func (m *SetPrimaryEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPrimaryEmailRequest.Unmarshal(m, b)
}
func (m *SetPrimaryEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPrimaryEmailRequest.Marshal(b, m, deterministic)
}
func (m *SetPrimaryEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPrimaryEmailRequest.Merge(m, src)
}
func (m *SetPrimaryEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SetPrimaryEmailRequest.Size(m)
}
func (m *SetPrimaryEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPrimaryEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPrimaryEmailRequest proto.InternalMessageInfo

func (m *SetPrimaryEmailRequest) GetUser() uint64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *SetPrimaryEmailRequest) GetEmailId() uint64 {
	if m != nil {
		return m.EmailId
	}
	return 0
}

type SetPrimaryEmailResponse struct {
	// Status of the request.
	Status               SetPrimaryEmailResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=email.SetPrimaryEmailResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SetPrimaryEmailResponse) Reset()         { *m = SetPrimaryEmailResponse{} }
func (m *SetPrimaryEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SetPrimaryEmailResponse) ProtoMessage()    {}
func (*SetPrimaryEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{10}
}

func (m *SetPrimaryEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPrimaryEmailResponse.Unmarshal(m, b)
}
func (m *SetPrimaryEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPrimaryEmailResponse.Marshal(b, m, deterministic)
}
func (m *SetPrimaryEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPrimaryEmailResponse.Merge(m, src)
}
func (m *SetPrimaryEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SetPrimaryEmailResponse.Size(m)
}
func (m *SetPrimaryEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPrimaryEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPrimaryEmailResponse proto.InternalMessageInfo

func (m *SetPrimaryEmailResponse) GetStatus() SetPrimaryEmailResponse_Status {
	if m != nil {
		return m.Status
	}
	return SetPrimaryEmailResponse_FAILURE
}

type GetUserRequest struct {
	// User that sent the request.
	User uint64 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	// Email to find the owner.
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{11}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUser() uint64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *GetUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserResponse struct {
	// Status of the request.
	Status GetUserResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=email.GetUserResponse_Status" json:"status,omitempty"`
	// User that owns the requested email address.
	User                 uint64   `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{12}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetStatus() GetUserResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetUserResponse_FAILURE
}

func (m *GetUserResponse) GetUser() uint64 {
	if m != nil {
		return m.User
	}
	return 0
}

func init() {
	proto.RegisterEnum("email.AddEmailResponse_Status", AddEmailResponse_Status_name, AddEmailResponse_Status_value)
	proto.RegisterEnum("email.GetEmailsResponse_Status", GetEmailsResponse_Status_name, GetEmailsResponse_Status_value)
	proto.RegisterEnum("email.ValidateEmailResponse_Status", ValidateEmailResponse_Status_name, ValidateEmailResponse_Status_value)
	proto.RegisterEnum("email.SetPrimaryEmailResponse_Status", SetPrimaryEmailResponse_Status_name, SetPrimaryEmailResponse_Status_value)
	proto.RegisterEnum("email.GetUserResponse_Status", GetUserResponse_Status_name, GetUserResponse_Status_value)
	proto.RegisterType((*EmailInfo)(nil), "email.EmailInfo")
	proto.RegisterType((*AddEmailRequest)(nil), "email.AddEmailRequest")
	proto.RegisterType((*AddEmailResponse)(nil), "email.AddEmailResponse")
	proto.RegisterType((*RemoveEmailRequest)(nil), "email.RemoveEmailRequest")
	proto.RegisterType((*RemoveEmailResponse)(nil), "email.RemoveEmailResponse")
	proto.RegisterType((*GetEmailsRequest)(nil), "email.GetEmailsRequest")
	proto.RegisterType((*GetEmailsResponse)(nil), "email.GetEmailsResponse")
	proto.RegisterType((*ValidateEmailRequest)(nil), "email.ValidateEmailRequest")
	proto.RegisterType((*ValidateEmailResponse)(nil), "email.ValidateEmailResponse")
	proto.RegisterType((*SetPrimaryEmailRequest)(nil), "email.SetPrimaryEmailRequest")
	proto.RegisterType((*SetPrimaryEmailResponse)(nil), "email.SetPrimaryEmailResponse")
	proto.RegisterType((*GetUserRequest)(nil), "email.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "email.GetUserResponse")
}

func init() { proto.RegisterFile("email.proto", fileDescriptor_6175298cb4ed6faa) }

var fileDescriptor_6175298cb4ed6faa = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4f, 0x73, 0x12, 0x4f,
	0x10, 0xfd, 0xed, 0x42, 0xf8, 0xd3, 0xfc, 0x12, 0xd6, 0x4e, 0x80, 0x0d, 0x4a, 0xc4, 0xb5, 0xb4,
	0xb8, 0x08, 0x15, 0x52, 0x1a, 0x4b, 0x4a, 0xab, 0x10, 0x36, 0x14, 0x16, 0x26, 0xd4, 0x12, 0x3c,
	0x78, 0xa1, 0x20, 0x3b, 0xd1, 0xb1, 0x80, 0xc5, 0x9d, 0x25, 0x55, 0x5e, 0xbc, 0x7a, 0xf0, 0xe0,
	0x37, 0xf0, 0xe0, 0xcd, 0x6f, 0x69, 0x65, 0x76, 0x20, 0x30, 0xfc, 0xd1, 0x18, 0x6f, 0x3b, 0x3d,
	0xaf, 0xdf, 0xcc, 0xeb, 0x79, 0xdd, 0x0b, 0x31, 0x32, 0xe8, 0xd2, 0x7e, 0x7e, 0xe4, 0x3a, 0x9e,
	0x83, 0x1b, 0x7c, 0x61, 0x7c, 0x86, 0xa8, 0x79, 0xf9, 0x51, 0x1f, 0x9e, 0x3b, 0xb8, 0x0b, 0x11,
	0x1e, 0xed, 0x50, 0x5b, 0x57, 0xb2, 0x4a, 0x2e, 0x68, 0x85, 0xf9, 0xba, 0x6e, 0xe3, 0x0e, 0xf8,
	0x09, 0xba, 0x9a, 0x55, 0x72, 0x51, 0xcb, 0x5f, 0xe0, 0x3d, 0xf8, 0x9f, 0xb2, 0xce, 0x45, 0xb7,
	0x4f, 0xed, 0xae, 0x47, 0x6c, 0x3d, 0x90, 0x55, 0x72, 0x11, 0x2b, 0x46, 0xd9, 0x9b, 0x49, 0x08,
	0x33, 0x00, 0x94, 0x75, 0x46, 0x2e, 0x1d, 0x74, 0xdd, 0x4f, 0x7a, 0x90, 0x03, 0xa2, 0x94, 0x35,
	0xfd, 0x80, 0x51, 0x82, 0x78, 0xd9, 0xb6, 0xf9, 0x15, 0x2c, 0xf2, 0x71, 0x4c, 0x98, 0x87, 0x08,
	0xc1, 0x31, 0x23, 0xae, 0xb8, 0x01, 0xff, 0x5e, 0x7e, 0xbc, 0xf1, 0x5d, 0x01, 0xed, 0x2a, 0x9b,
	0x8d, 0x9c, 0x21, 0x23, 0xf8, 0x04, 0x42, 0xcc, 0xeb, 0x7a, 0x63, 0xc6, 0x09, 0xb6, 0x8a, 0x7b,
	0x79, 0x5f, 0xb6, 0x0c, 0xcc, 0xb7, 0x38, 0xca, 0x12, 0xe8, 0x39, 0xf1, 0xea, 0x9c, 0x78, 0xe3,
	0x10, 0x42, 0x3e, 0x18, 0x63, 0x10, 0x3e, 0x2a, 0xd7, 0x1b, 0x6d, 0xcb, 0xd4, 0xfe, 0xbb, 0x5c,
	0xb4, 0xda, 0x95, 0x8a, 0xd9, 0x6a, 0x69, 0x0a, 0x6e, 0x43, 0xbc, 0xda, 0x6e, 0x36, 0xea, 0x95,
	0xf2, 0xa9, 0xd9, 0x31, 0x5f, 0x97, 0xeb, 0x0d, 0x4d, 0x35, 0x2a, 0x80, 0x16, 0x19, 0x38, 0x17,
	0xe4, 0xb7, 0x02, 0xd7, 0x9c, 0x9e, 0x80, 0xed, 0x39, 0x12, 0xff, 0xfa, 0xc6, 0x43, 0xd0, 0x6a,
	0xc4, 0xe3, 0x31, 0xb6, 0x86, 0xd9, 0xf8, 0xa9, 0xc0, 0xad, 0x19, 0xa0, 0xa8, 0xd2, 0xa1, 0x54,
	0xa5, 0xbb, 0xa2, 0x4a, 0x0b, 0x48, 0xb9, 0x4c, 0x39, 0x08, 0x71, 0x24, 0xd3, 0xd5, 0x6c, 0x20,
	0x17, 0x2b, 0x6a, 0x22, 0x71, 0xea, 0x22, 0x4b, 0xec, 0x1b, 0xfb, 0x7f, 0x50, 0xb5, 0x4d, 0x88,
	0x1e, 0x9f, 0x9c, 0x76, 0x8e, 0x4e, 0xda, 0xc7, 0x55, 0x4d, 0x35, 0x4c, 0xd8, 0x99, 0x38, 0xe7,
	0x26, 0x15, 0xfb, 0xa2, 0x40, 0x42, 0xe2, 0x11, 0xb2, 0x4b, 0x92, 0xec, 0xfb, 0xe2, 0xf6, 0x4b,
	0xd1, 0x92, 0xf4, 0xbf, 0x11, 0x54, 0x83, 0x64, 0x8b, 0x78, 0xc2, 0xec, 0x37, 0x91, 0xf4, 0x55,
	0x81, 0xd4, 0x02, 0x93, 0x10, 0xf5, 0x5c, 0x12, 0xf5, 0x40, 0x88, 0x5a, 0x81, 0xff, 0x07, 0xb2,
	0x9e, 0xc1, 0x56, 0x8d, 0x78, 0x6d, 0x46, 0xdc, 0xeb, 0x37, 0xed, 0x37, 0x05, 0xe2, 0xd3, 0x64,
	0xa1, 0xe0, 0xb1, 0xa4, 0x20, 0x73, 0xe5, 0xc6, 0x59, 0x9c, 0xec, 0xc5, 0xc9, 0xa1, 0xea, 0x8c,
	0xdd, 0xaf, 0xaf, 0xa6, 0xf8, 0x23, 0x00, 0x1b, 0xbc, 0x42, 0x58, 0x82, 0xc8, 0x64, 0x4c, 0x60,
	0x72, 0x61, 0x6e, 0x70, 0xa5, 0xe9, 0xd4, 0x8a, 0x79, 0x82, 0x55, 0x88, 0xcd, 0xf4, 0x29, 0xee,
	0x0a, 0xdc, 0xe2, 0x00, 0x48, 0xa7, 0x97, 0x6d, 0x09, 0x96, 0x17, 0x10, 0x9d, 0xf6, 0x20, 0xa6,
	0x16, 0xbb, 0xd2, 0x67, 0xd0, 0x57, 0xb5, 0x2b, 0xbe, 0x82, 0xcd, 0x39, 0x33, 0xe3, 0xed, 0xe5,
	0x16, 0xf7, 0x79, 0xee, 0xac, 0xf3, 0x3f, 0x36, 0x21, 0x2e, 0x79, 0x08, 0x33, 0xab, 0xbc, 0xe5,
	0xf3, 0xed, 0xad, 0xb7, 0x1e, 0x3e, 0x85, 0xb0, 0x78, 0x53, 0x4c, 0xc8, 0x6f, 0xec, 0x33, 0x24,
	0x97, 0x3f, 0xfd, 0xcb, 0x83, 0xb7, 0xfb, 0xef, 0xa8, 0xf7, 0x7e, 0xdc, 0xcb, 0x9f, 0x39, 0x83,
	0x82, 0xeb, 0xf4, 0x9c, 0x0f, 0xce, 0x90, 0xb0, 0xc2, 0x59, 0xdf, 0x19, 0xdb, 0x8f, 0x78, 0x4e,
	0xc1, 0x26, 0xe7, 0x74, 0x48, 0x3d, 0xea, 0x0c, 0x0b, 0x3c, 0xd0, 0x0b, 0xf1, 0x7f, 0xdd, 0xc1,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x2c, 0xdb, 0x95, 0xfa, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailClient is the client API for Email service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailClient interface {
	// AddEmail adds a new email with some initial tags to a user.
	AddEmail(ctx context.Context, in *AddEmailRequest, opts ...grpc.CallOption) (*AddEmailResponse, error)
	// RemoveEmail deletes an email with all its tags.
	// The email with the PRIMARY tag cannot be removed.
	RemoveEmail(ctx context.Context, in *RemoveEmailRequest, opts ...grpc.CallOption) (*RemoveEmailResponse, error)
	// GetEmails returns a list of all emails linked to the user.
	GetEmails(ctx context.Context, in *GetEmailsRequest, opts ...grpc.CallOption) (*GetEmailsResponse, error)
	// ValidateEmail adds the VALIDATED tag to the email.
	ValidateEmail(ctx context.Context, in *ValidateEmailRequest, opts ...grpc.CallOption) (*ValidateEmailResponse, error)
	// SetPrimaryEmail sets an existing email as primary email for a user.
	// Moves the PRIMARY tag of the user account to the provided email.
	// The primary email is used as default email for all purposes.
	SetPrimaryEmail(ctx context.Context, in *SetPrimaryEmailRequest, opts ...grpc.CallOption) (*SetPrimaryEmailResponse, error)
	// GetUser returns the owner of an email address.
	// E.g. for contact requests.
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type emailClient struct {
	cc *grpc.ClientConn
}

func NewEmailClient(cc *grpc.ClientConn) EmailClient {
	return &emailClient{cc}
}

func (c *emailClient) AddEmail(ctx context.Context, in *AddEmailRequest, opts ...grpc.CallOption) (*AddEmailResponse, error) {
	out := new(AddEmailResponse)
	err := c.cc.Invoke(ctx, "/email.Email/AddEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) RemoveEmail(ctx context.Context, in *RemoveEmailRequest, opts ...grpc.CallOption) (*RemoveEmailResponse, error) {
	out := new(RemoveEmailResponse)
	err := c.cc.Invoke(ctx, "/email.Email/RemoveEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) GetEmails(ctx context.Context, in *GetEmailsRequest, opts ...grpc.CallOption) (*GetEmailsResponse, error) {
	out := new(GetEmailsResponse)
	err := c.cc.Invoke(ctx, "/email.Email/GetEmails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) ValidateEmail(ctx context.Context, in *ValidateEmailRequest, opts ...grpc.CallOption) (*ValidateEmailResponse, error) {
	out := new(ValidateEmailResponse)
	err := c.cc.Invoke(ctx, "/email.Email/ValidateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) SetPrimaryEmail(ctx context.Context, in *SetPrimaryEmailRequest, opts ...grpc.CallOption) (*SetPrimaryEmailResponse, error) {
	out := new(SetPrimaryEmailResponse)
	err := c.cc.Invoke(ctx, "/email.Email/SetPrimaryEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/email.Email/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServer is the server API for Email service.
type EmailServer interface {
	// AddEmail adds a new email with some initial tags to a user.
	AddEmail(context.Context, *AddEmailRequest) (*AddEmailResponse, error)
	// RemoveEmail deletes an email with all its tags.
	// The email with the PRIMARY tag cannot be removed.
	RemoveEmail(context.Context, *RemoveEmailRequest) (*RemoveEmailResponse, error)
	// GetEmails returns a list of all emails linked to the user.
	GetEmails(context.Context, *GetEmailsRequest) (*GetEmailsResponse, error)
	// ValidateEmail adds the VALIDATED tag to the email.
	ValidateEmail(context.Context, *ValidateEmailRequest) (*ValidateEmailResponse, error)
	// SetPrimaryEmail sets an existing email as primary email for a user.
	// Moves the PRIMARY tag of the user account to the provided email.
	// The primary email is used as default email for all purposes.
	SetPrimaryEmail(context.Context, *SetPrimaryEmailRequest) (*SetPrimaryEmailResponse, error)
	// GetUser returns the owner of an email address.
	// E.g. for contact requests.
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

// UnimplementedEmailServer can be embedded to have forward compatible implementations.
type UnimplementedEmailServer struct {
}

func (*UnimplementedEmailServer) AddEmail(ctx context.Context, req *AddEmailRequest) (*AddEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEmail not implemented")
}
func (*UnimplementedEmailServer) RemoveEmail(ctx context.Context, req *RemoveEmailRequest) (*RemoveEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveEmail not implemented")
}
func (*UnimplementedEmailServer) GetEmails(ctx context.Context, req *GetEmailsRequest) (*GetEmailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmails not implemented")
}
func (*UnimplementedEmailServer) ValidateEmail(ctx context.Context, req *ValidateEmailRequest) (*ValidateEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateEmail not implemented")
}
func (*UnimplementedEmailServer) SetPrimaryEmail(ctx context.Context, req *SetPrimaryEmailRequest) (*SetPrimaryEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPrimaryEmail not implemented")
}
func (*UnimplementedEmailServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterEmailServer(s *grpc.Server, srv EmailServer) {
	s.RegisterService(&_Email_serviceDesc, srv)
}

func _Email_AddEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).AddEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/email.Email/AddEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).AddEmail(ctx, req.(*AddEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_RemoveEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).RemoveEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/email.Email/RemoveEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).RemoveEmail(ctx, req.(*RemoveEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_GetEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).GetEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/email.Email/GetEmails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).GetEmails(ctx, req.(*GetEmailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_ValidateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).ValidateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/email.Email/ValidateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).ValidateEmail(ctx, req.(*ValidateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_SetPrimaryEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPrimaryEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).SetPrimaryEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/email.Email/SetPrimaryEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).SetPrimaryEmail(ctx, req.(*SetPrimaryEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/email.Email/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Email_serviceDesc = grpc.ServiceDesc{
	ServiceName: "email.Email",
	HandlerType: (*EmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEmail",
			Handler:    _Email_AddEmail_Handler,
		},
		{
			MethodName: "RemoveEmail",
			Handler:    _Email_RemoveEmail_Handler,
		},
		{
			MethodName: "GetEmails",
			Handler:    _Email_GetEmails_Handler,
		},
		{
			MethodName: "ValidateEmail",
			Handler:    _Email_ValidateEmail_Handler,
		},
		{
			MethodName: "SetPrimaryEmail",
			Handler:    _Email_SetPrimaryEmail_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Email_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email.proto",
}
