name: Go
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download

    - name: Generate code
      run: go generate

    - name: Test
      run: go test -v ./...
      env:
        COCKROACH_CONNECTION: host=localhost port=26257 user=email_test dbname=email_test sslmode=disable
        PORT: 8080

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download

    - name: Generate code
      run: go generate

    - name: Build
      run: go build -v .
